using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UniCare.Domain.Entities;

namespace UniCare.Infrastructure.Data.Configurations;

public class MedicalDocumentConfiguration : IEntityTypeConfiguration<MedicalDocument>
{
    public void Configure(EntityTypeBuilder<MedicalDocument> builder)
    {
        // The student's document list is the query that matters, newest first.
        builder.HasIndex(d => new { d.StudentId, d.UploadedAt });

        // Staff need to find documents waiting to be processed.
        builder.HasIndex(d => d.Status);

        // Storage keys are generated by us and must be unique — a collision would
        // silently overwrite someone else's medical document.
        builder.HasIndex(d => d.StorageKey).IsUnique();

        builder.Property(d => d.OriginalFileName).HasMaxLength(255);
        builder.Property(d => d.StorageKey).HasMaxLength(255);
        builder.Property(d => d.ContentType).HasMaxLength(128);
    }
}
